# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cody/wall-e

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cody/wall-e

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cody/wall-e/CMakeFiles /home/cody/wall-e/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cody/wall-e/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build/disparity

# Build rule for target.
build/disparity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/disparity
.PHONY : build/disparity

# fast build rule for target.
build/disparity/fast:
	$(MAKE) -f CMakeFiles/build/disparity.dir/build.make CMakeFiles/build/disparity.dir/build
.PHONY : build/disparity/fast

#=============================================================================
# Target rules for targets named build/intrinsic

# Build rule for target.
build/intrinsic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/intrinsic
.PHONY : build/intrinsic

# fast build rule for target.
build/intrinsic/fast:
	$(MAKE) -f CMakeFiles/build/intrinsic.dir/build.make CMakeFiles/build/intrinsic.dir/build
.PHONY : build/intrinsic/fast

#=============================================================================
# Target rules for targets named build/stereo

# Build rule for target.
build/stereo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/stereo
.PHONY : build/stereo

# fast build rule for target.
build/stereo/fast:
	$(MAKE) -f CMakeFiles/build/stereo.dir/build.make CMakeFiles/build/stereo.dir/build
.PHONY : build/stereo/fast

src/calibrate_stereo.o: src/calibrate_stereo.cpp.o
.PHONY : src/calibrate_stereo.o

# target to build an object file
src/calibrate_stereo.cpp.o:
	$(MAKE) -f CMakeFiles/build/stereo.dir/build.make CMakeFiles/build/stereo.dir/src/calibrate_stereo.cpp.o
.PHONY : src/calibrate_stereo.cpp.o

src/calibrate_stereo.i: src/calibrate_stereo.cpp.i
.PHONY : src/calibrate_stereo.i

# target to preprocess a source file
src/calibrate_stereo.cpp.i:
	$(MAKE) -f CMakeFiles/build/stereo.dir/build.make CMakeFiles/build/stereo.dir/src/calibrate_stereo.cpp.i
.PHONY : src/calibrate_stereo.cpp.i

src/calibrate_stereo.s: src/calibrate_stereo.cpp.s
.PHONY : src/calibrate_stereo.s

# target to generate assembly for a file
src/calibrate_stereo.cpp.s:
	$(MAKE) -f CMakeFiles/build/stereo.dir/build.make CMakeFiles/build/stereo.dir/src/calibrate_stereo.cpp.s
.PHONY : src/calibrate_stereo.cpp.s

src/find_intrinsic.o: src/find_intrinsic.cpp.o
.PHONY : src/find_intrinsic.o

# target to build an object file
src/find_intrinsic.cpp.o:
	$(MAKE) -f CMakeFiles/build/intrinsic.dir/build.make CMakeFiles/build/intrinsic.dir/src/find_intrinsic.cpp.o
.PHONY : src/find_intrinsic.cpp.o

src/find_intrinsic.i: src/find_intrinsic.cpp.i
.PHONY : src/find_intrinsic.i

# target to preprocess a source file
src/find_intrinsic.cpp.i:
	$(MAKE) -f CMakeFiles/build/intrinsic.dir/build.make CMakeFiles/build/intrinsic.dir/src/find_intrinsic.cpp.i
.PHONY : src/find_intrinsic.cpp.i

src/find_intrinsic.s: src/find_intrinsic.cpp.s
.PHONY : src/find_intrinsic.s

# target to generate assembly for a file
src/find_intrinsic.cpp.s:
	$(MAKE) -f CMakeFiles/build/intrinsic.dir/build.make CMakeFiles/build/intrinsic.dir/src/find_intrinsic.cpp.s
.PHONY : src/find_intrinsic.cpp.s

src/stereo_disparity.o: src/stereo_disparity.cpp.o
.PHONY : src/stereo_disparity.o

# target to build an object file
src/stereo_disparity.cpp.o:
	$(MAKE) -f CMakeFiles/build/disparity.dir/build.make CMakeFiles/build/disparity.dir/src/stereo_disparity.cpp.o
.PHONY : src/stereo_disparity.cpp.o

src/stereo_disparity.i: src/stereo_disparity.cpp.i
.PHONY : src/stereo_disparity.i

# target to preprocess a source file
src/stereo_disparity.cpp.i:
	$(MAKE) -f CMakeFiles/build/disparity.dir/build.make CMakeFiles/build/disparity.dir/src/stereo_disparity.cpp.i
.PHONY : src/stereo_disparity.cpp.i

src/stereo_disparity.s: src/stereo_disparity.cpp.s
.PHONY : src/stereo_disparity.s

# target to generate assembly for a file
src/stereo_disparity.cpp.s:
	$(MAKE) -f CMakeFiles/build/disparity.dir/build.make CMakeFiles/build/disparity.dir/src/stereo_disparity.cpp.s
.PHONY : src/stereo_disparity.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... build/disparity"
	@echo "... build/intrinsic"
	@echo "... build/stereo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/calibrate_stereo.o"
	@echo "... src/calibrate_stereo.i"
	@echo "... src/calibrate_stereo.s"
	@echo "... src/find_intrinsic.o"
	@echo "... src/find_intrinsic.i"
	@echo "... src/find_intrinsic.s"
	@echo "... src/stereo_disparity.o"
	@echo "... src/stereo_disparity.i"
	@echo "... src/stereo_disparity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

